services:
  app:
    container_name: oont-api
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/oont?sslmode=disable
    depends_on:
      - postgres
    networks:
      - oont

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oont
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oont

volumes:
  postgres_data:
    name: pg-oont-api

networks:
  oont:
    name: oont-network
